In [1]:
import pandas as pd
data = pd.read_csv("assignment dataset3.csv")
data

       Age  Income Student Creditrating Buyscomputer
0    Youth    High      No         Fair           No
1    Youth    High      No    Excellent           No
2   Middle    High      No         Fair          Yes
3   Senior  Medium      No         Fair          Yes
4   Senior     Low     Yes         Fair          Yes
5   Middle     Low     Yes    Excellent           No
6   Senior     Low     Yes    Excellent          Yes
7    Youth  Medium      No         Fair           No
8    Youth     Low     Yes         Fair          Yes
9   Senior  Medium     Yes         Fair          Yes
10   Youth  Medium     Yes    Excellent          Yes

In [3]:
data.info

<bound method DataFrame.info of        Age  Income Student Creditrating Buyscomputer
0    Youth    High      No         Fair           No
1    Youth    High      No    Excellent           No
2   Middle    High      No         Fair          Yes
3   Senior  Medium      No         Fair          Yes
4   Senior     Low     Yes         Fair          Yes
5   Middle     Low     Yes    Excellent           No
6   Senior     Low     Yes    Excellent          Yes
7    Youth  Medium      No         Fair           No
8    Youth     Low     Yes         Fair          Yes
9   Senior  Medium     Yes         Fair          Yes
10   Youth  Medium     Yes    Excellent          Yes>

In [ ]:
data.iloc[:, 1]

In [ ]:
data.iloc[1]

In [ ]:
y = data.iloc[:, -1]
y

In [ ]:
x = data.iloc[:, :-1]
x

In [ ]:
y.shape

In [ ]:
x = data.iloc[:, :-3]
x

In [ ]:
data.iloc[:5]

In [37]:
x['Age']=X['Age'].map({'Youth':1,'Midle':2,'senior':3})
x['Income']=X['Income'].map({'High':1,'Midle':2,'Low':3})
x['Student']=X['Student'].map({'No':0,'Yas':1})
x['Creditrating']=X['Creditrating'].map({'Fair':0,'Excellent':1})
X

C:\Users\student\AppData\Local\Temp\ipykernel_10604\3475259963.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Age']=X['Age'].map({'Youth':1,'Midle':2,'senior':3})
C:\Users\student\AppData\Local\Temp\ipykernel_10604\3475259963.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Income']=X['Income'].map({'High':1,'Midle':2,'Low':3})
C:\Users\student\AppData\Local\Temp\ipykernel_10604\3475259963.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Student']=X['Student'].map({'No':0,'Yas':1})
C:\Users\student\AppData\Local\Temp\ipykernel_10604\3475259963.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Creditrating']=X['Creditrating'].map({'Fair':0,'Excellent':1})

       Age  Income Student Creditrating
0    Youth    High      No         Fair
1    Youth    High      No    Excellent
2   Middle    High      No         Fair
3   Senior  Medium      No         Fair
4   Senior     Low     Yes         Fair
5   Middle     Low     Yes    Excellent
6   Senior     Low     Yes    Excellent
7    Youth  Medium      No         Fair
8    Youth     Low     Yes         Fair
9   Senior  Medium     Yes         Fair
10   Youth  Medium     Yes    Excellent

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X,Y)